"""
Challenge Manager — Structured folder creation and metadata tracking for CTF challenges.
"""

from __future__ import annotations

import json
import os
import shutil
import subprocess
from datetime import datetime
from pathlib import Path
from typing import List, Optional

from milkyway.core import config
from milkyway.core.db import Challenge, SaturnDB


README_TEMPLATE = """# {name}

**Category**: {category}  
**Created**: {created}  
**URL**: {url}  

## Notes

{notes}

## Solution

<!-- Document your solution path here -->

## Files

<!-- List important files and their purpose -->

## Commands Used

<!-- Key commands that led to the flag -->

---
*Generated by [MilkyWay](https://github.com/kazim-45/milkyway) 🌌*
"""


class ChallengeManager:
    """Creates and manages CTF challenge workspaces."""

    CATEGORIES = ["web", "crypto", "forensics", "rev", "pwn", "misc", "osint", "mobile", "cloud"]

    def __init__(self, db: Optional[SaturnDB] = None):
        self.db = db or SaturnDB()
        self.challenges_dir = config.challenges_dir()

    def new(
        self,
        name: str,
        category: str = "misc",
        url: Optional[str] = None,
        tags: Optional[List[str]] = None,
        description: str = "",
    ) -> Challenge:
        """Create a new challenge workspace."""
        # Validate
        if not name.replace("_", "").replace("-", "").isalnum():
            raise ValueError(f"Challenge name '{name}' must be alphanumeric (underscores/hyphens OK)")
        if self.db.get_challenge(name):
            raise ValueError(f"Challenge '{name}' already exists")

        folder = self.challenges_dir / name
        folder.mkdir(parents=True, exist_ok=True)

        # Scaffold structure
        (folder / ".milkyway").mkdir(exist_ok=True)
        (folder / "files").mkdir(exist_ok=True)
        (folder / "solutions").mkdir(exist_ok=True)
        (folder / "outputs").mkdir(exist_ok=True)

        # Per-challenge Saturn DB
        local_db = SaturnDB(folder / ".milkyway" / "local.db")

        # Challenge config
        cfg = {
            "name": name,
            "category": category,
            "url": url or "",
            "tags": tags or [],
            "created": datetime.now().isoformat(),
            "description": description,
        }
        (folder / ".milkyway" / "config.json").write_text(
            json.dumps(cfg, indent=2), encoding="utf-8"
        )

        # notes.md
        notes_path = folder / "notes.md"
        notes_path.write_text(
            f"# Notes — {name}\n\n"
            f"**Category**: {category}\n"
            f"**URL**: {url or 'N/A'}\n\n"
            f"## Observations\n\n"
            f"<!-- Add your notes here -->\n",
            encoding="utf-8",
        )

        # README
        readme_path = folder / "README.md"
        readme_path.write_text(
            README_TEMPLATE.format(
                name=name,
                category=category,
                created=datetime.now().strftime("%Y-%m-%d %H:%M"),
                url=url or "N/A",
                notes=description or "<!-- Add challenge description here -->",
            ),
            encoding="utf-8",
        )

        # solve.py starter
        solve_path = folder / "solutions" / "solve.py"
        solve_path.write_text(
            f'#!/usr/bin/env python3\n"""Solution for {name}"""\n\n# {url or ""}\n\ndef main():\n    pass\n\nif __name__ == "__main__":\n    main()\n',
            encoding="utf-8",
        )

        # Register in global DB
        cid = self.db.create_challenge(
            name=name,
            category=category,
            folder_path=str(folder),
            url=url,
            tags=tags or [],
        )

        return self.db.get_challenge_by_id(cid)

    def get(self, name: str) -> Optional[Challenge]:
        return self.db.get_challenge(name)

    def list_all(self, category: Optional[str] = None) -> List[Challenge]:
        return self.db.list_challenges(category=category)

    def cd_path(self, name: str) -> Optional[str]:
        ch = self.db.get_challenge(name)
        return ch.folder_path if ch else None

    def add_note(self, name: str, text: str) -> None:
        ch = self.db.get_challenge(name)
        if not ch:
            raise ValueError(f"Challenge '{name}' not found")

        notes_path = ch.path / "notes.md"
        timestamp = datetime.now().strftime("%Y-%m-%d %H:%M")
        with open(notes_path, "a", encoding="utf-8") as f:
            f.write(f"\n### {timestamp}\n\n{text}\n")

        # Update DB notes
        existing = ch.notes or ""
        self.db.update_challenge_notes(name, existing + f"\n[{timestamp}] {text}")

    def delete(self, name: str, confirm: bool = False) -> bool:
        ch = self.db.get_challenge(name)
        if not ch:
            return False
        if confirm:
            if ch.path.exists():
                shutil.rmtree(ch.path)
            return self.db.delete_challenge(name)
        return False

    def open_in_editor(self, name: str) -> None:
        ch = self.db.get_challenge(name)
        if not ch:
            raise ValueError(f"Challenge '{name}' not found")
        editor = os.environ.get("EDITOR", "nano")
        subprocess.run([editor, str(ch.path / "notes.md")])

    def get_current_challenge(self) -> Optional[Challenge]:
        """Detect challenge from cwd."""
        current = Path.cwd()
        for parent in [current, *current.parents]:
            cfg_file = parent / ".milkyway" / "config.json"
            if cfg_file.exists():
                try:
                    cfg = json.loads(cfg_file.read_text())
                    return self.db.get_challenge(cfg["name"])
                except Exception:
                    pass
        return None
